import { LinkedList } from "./linkedList.js";

let instanceOfLinkedList = LinkedList();
//console.log(instanceOfLinkedList);
instanceOfLinkedList.append(4);
instanceOfLinkedList.preppend(1);
instanceOfLinkedList.append(5);
instanceOfLinkedList.append("Diego");
instanceOfLinkedList.append("Samayoa");
//console.log("Size", instanceOfLinkedList.getSize());
//console.log("Head", instanceOfLinkedList.getHead());
//console.log("Tail", instanceOfLinkedList.getTail());
//console.log("At Index", instanceOfLinkedList.atIndex(0));
//console.log("xd");
//instanceOfLinkedList.toString();
//instanceOfLinkedList.pop();
//console.log("Size", instanceOfLinkedList.getSize());
//console.log(instanceOfLinkedList.contains(5));
//console.log(instanceOfLinkedList.find("Samayoa"));
console.log(instanceOfLinkedList.toString());
